### ISSUE TITLE
atob is returning string

### ISSUE THREAD

**Issue by gkucmierz** [coolaj86/node-browser-compat#7]
atob function is returning typeof string instead binary buffer

**Comment by coolaj86** [comment]
That is correct. That's how `window.atob` has worked since the 90s and I don't think they plan on changing it to an ArrayBuffer anytime soon.

**Comment by gkucmierz** [comment]
No problem, thx for answer. I just found https://github.com/beatgammit/base64-js

**Comment by coolaj86** [comment]
Yep.

Also, if you're targeting newer browsers: https://git.daplie.com/Daplie/unibabel-js

But if you're targeting node you can just use `Buffer.from('aGVsbG8sIHdvcmxk', 'base64')`

However, beatgammit's will also work in web workers, which unibabel will not (because web workers do not implement all of the DOM spec - like atob)
